In [1]:
import numpy as np

In [2]:
def householder(A):

    n = A.shape[0]
    v = np.zeros(n, dtype=np.double)
    u = np.zeros(n, dtype=np.double)
    z = np.zeros(n, dtype=np.double)

    for k in range(0, n - 2):

        if np.isclose(A[k + 1, k], 0.0):
            α = -np.sqrt(np.sum(A[(k + 1) :, k] ** 2))
        else:
            α = -np.sign(A[k + 1, k]) * np.sqrt(np.sum(A[(k + 1) :, k] ** 2))

        two_r_squared = α ** 2 - α * A[k + 1, k]
        v[k] = 0.0
        v[k + 1] = A[k + 1, k] - α
        v[(k + 2) :] = A[(k + 2) :, k]
        u[k:] = 1.0 / two_r_squared * np.dot(A[k:, (k + 1) :], v[(k + 1) :])
        z[k:] = u[k:] - np.dot(u, v) / (2.0 * two_r_squared) * v[k:]

        for l in range(k + 1, n - 1):

            A[(l + 1) :, l] = (
                A[(l + 1) :, l] - v[l] * z[(l + 1) :] - v[(l + 1) :] * z[l]
            )
            A[l, (l + 1) :] = A[(l + 1) :, l]
            A[l, l] = A[l, l] - 2 * v[l] * z[l]

        A[-1, -1] = A[-1, -1] - 2 * v[-1] * z[-1]
        A[k, (k + 2) :] = 0.0
        A[(k + 2) :, k] = 0.0

        A[k + 1, k] = A[k + 1, k] - v[k + 1] * z[k]
        A[k, k + 1] = A[k + 1, k]

In [9]:
# test the implementation

# generate symmetric matrix
A = np.array([[0.7868,   0.0193, 0.5206,   0.1400],
   [0.0193,   0.4049,   0.3447,   0.5439],
   [0.5206,   0.3447,   0.2742,   0.5219],
   [0.1400,   0.5439,   0.5219,   0.8571]])

eigen_values = np.linalg.eigvals(A)
print(np.round(np.sort(eigen_values), 10))

# apply householder reduction
householder(A)

# check if the result is tridiagonal
print(np.round(A, 10))

[-0.21825584  0.04006711  0.81952922  1.68165951]
[[ 0.7868     -0.53944124  0.          0.        ]
 [-0.53944124  0.6089661  -0.77042552  0.        ]
 [ 0.         -0.77042552  0.88734476 -0.02094449]
 [ 0.          0.         -0.02094449  0.03988914]]


In [10]:
# calculate eigen values
eigen_values = np.linalg.eigvalsh(A)
print(np.round(np.sort(eigen_values), 10))


[-0.21825584  0.04006711  0.81952922  1.68165951]
